name: Binary Release Build

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build in Docker
        run: |
          # Get the latest stable rust toolchain version available
          TOOLCHAIN=$(curl -s 'https://static.rust-lang.org/dist/channel-rust-stable.toml' | awk '/\[pkg.rust\]/ {getline;print;}' | sed -r 's/^version = "([0-9.]+) .*/\1/')
          scripts/docker-build-linux.sh "$TOOLCHAIN"
        env:
          BUILD_ARCH: x86_64
          RELAY_FEATURES:

      - name: Bundle Debug File
        run: |
          cd target/x86_64-unknown-linux-gnu/release/
          zip relay-Linux-x86_64-debug.zip relay.debug
          mv relay relay-Linux-x86_64

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: target/x86_64-unknown-linux-gnu/release/relay-Linux-x86_64*
